package legalguard.astrosp_awesome_osint_list

# Guardrail for: Astrosp/Awesome-OSINT-List
# Sector: Uncategorized | Modality: structured | Risk tier: unclassified
#
# This is a default-deny stub generated by LegalGuard. Fill in the real
# conditions for each regulatory mandate listed in REGULATORY_PROVENANCE.md
# before treating this as enforceable -- see that file for what each clause
# actually requires.

default allow := false

allow if {
    input.compliance_checks_passed == true
    input.human_review_confirmed == true
}
